import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Nav from "./_components/nav";
import { Suspense } from "react";
import Analytics from "./analytics";
import Script from "next/script";
import JivoChatWidget from "./_components/jivo";
import Link from "next/link";
import { WhatsApp } from "./_components/icons";
import { EnvelopeIcon, MapPinIcon, PhoneIcon } from "@heroicons/react/20/solid";
import SocialNetworks from "./_components/social";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Panel Prefabricados para Naves Industriales | Smart Panel",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Head>
				{/* Your chatbot script goes here */}
				
				<meta charSet="UTF-8" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, shrink-to-fit=no"
				/>
				<meta httpEquiv="X-UA-Compatible" content="IE=edge" />
				<meta
					name="robots"
					content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"
				/>
				<meta
					name="description"
					content="Paneles tipo sándwich con núcleo EPS para construir oficinas prefabricadas funcionales, térmicas y modulares. Instalación rápida"
				/>
				<link rel="canonical" href="https://smartpanel.mx/" />
				<meta property="og:locale" content="es_MX" />
				<meta property="og:type" content="article" />
				<meta property="og:title" content="Smart Panel" />
				<meta
					property="og:description"
					content="Paneles tipo sándwich con núcleo EPS para construir oficinas prefabricadas funcionales, térmicas y modulares. Instalación rápida"
				/>
				<meta property="og:url" content="https://smartpanel.mx/" />
				<meta property="og:site_name" content="Smart Panel" />
				<meta
					property="article:modified_time"
					content="2025-07-07T22:02:21+00:00"
				/>
				<meta property="og:image:width" content="800" />
				<meta property="og:image:height" content="600" />
				<meta property="og:image:type" content="image/webp" />
				<meta name="twitter:card" content="summary_large_image" />
				<meta name="twitter:label1" content="Tiempo de lectura" />
				<meta name="twitter:data1" content="2 minutos" />
				<link rel="dns-prefetch" href="//code.jivosite.com" />
				<link
					rel="alternate"
					type="application/rss+xml"
					title="Smart Panel » Feed"
					href="https://smartpanel.mx/feed/"
				/>
				<link
					rel="alternate"
					type="application/rss+xml"
					title="Smart Panel » RSS de los comentarios"
					href="https://smartpanel.mx/comments/feed/"
				/>
				<link rel="icon" href="/smart-panel-vf-80x80.jpg" sizes="32x32" />
				<link rel="icon" href="/smart-panel-vf-300x300.jpg" sizes="192x192" />
				<link rel="apple-touch-icon" href="/smart-panel-vf-300x300.jpg" />
				<meta
					name="msapplication-TileImage"
					content="/smart-panel-vf-300x300.jpg"
				/>
			</Head>

			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Nav />
				{children}
				{/* Footer */}
				<Script src="//code.jivosite.com/widget/4mwghIbKQO" async />

				<footer className="bg-black text-white py-12">
					<div className="max-w-7xl mx-auto px-6 grid md:grid-cols-4 gap-8">
						<div>
							<img
								src="/LOGO-COLOR-SMART-PANEL-SLD.png"
								alt="SmartPanel logo footer"
								className="mb-4 max-w-60"
							/>
						</div>
						<div>
							<h3 className="font-semibold text-lg mb-2">Productos</h3>
							<ul className="space-y-2 text-sm divide-y divide-gray-800">
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/productos/panel-muro"
									>
										Panel Muro
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/productos/panel-techo"
									>
										Panel Techo
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/productos/politica-calidad"
									>
										Política de calidad
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/productos/aviso-privacidad"
									>
										Aviso de Privacidad
									</Link>
								</li>
							</ul>
						</div>
						<div>
							<h3 className="font-semibold text-lg mb-2">Aplicaciones</h3>
							<ul className="space-y-2 divide-y divide-gray-800 text-sm">
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/aplicaciones/naves-industriales"
									>
										Naves Industriales
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/aplicaciones/residenciales-habitacionales"
									>
										Residenciales Habitacionales
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/aplicaciones/oficinas"
									>
										Oficinas
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/aplicaciones/aulas-prefabricadas"
									>
										Aulas
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/aplicaciones/bodegas-almacenes"
									>
										Bodegas/Almacenes
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/aplicaciones/camaras"
									>
										Cámaras
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/aplicaciones/techos"
									>
										Techos
									</Link>
								</li>
								<li className="py-2">
									<Link
										className="hover:text-green-500"
										href="/aplicaciones/hospitales"
									>
										Hospitales
									</Link>
								</li>
							</ul>
						</div>
						<div>
							<h3 className="font-semibold text-lg mb-2">Contáctanos</h3>
							<div>
								<Link
									href="https://maps.app.goo.gl/qzN8NWH2MQxMEBAz9"
									className="text-sm mb-2 hover:text-green-500"
									target="_blank"
									rel="noopener noreferrer"
								>
									<MapPinIcon className="inline mr-2 text-green-500 size-4" />{" "}
									Fracción de la Parcela 3 No. 60, int. Z#2, Praderas de los
									Angeles, Querétaro, CP. 76908
								</Link>
							</div>
							<div>
								<Link href="tel:+525610197622" className="text-sm mb-2">
									{" "}
									<PhoneIcon className="inline mr-2 text-green-500 size-4" /> +52 123 456
									7890
								</Link>
							</div>
							<Link
								href="mailto:atencionaclientes1@smartpanel.mx"
								className="text-sm mb-2"
							>
								<EnvelopeIcon className="inline mr-2 text-green-500 size-4" />{" "}
									atencionaclientes1@smartpanel.mx
							</Link>
							<div className="text-white text-sm mt-4 mb-2">
								<p>Redes sociales</p>
							</div>
							<div className="fill-green-500">

							<SocialNetworks className="fill-green-500"/>
							</div>
						</div>
					</div>
					<div className="text-center mt-10 text-sm text-green-500">
						Copyright © 2025 SMART PANEL | Designed by ROC Worldwide Agency and
						Optimized by Luis ROC | All Rights Reserved
					</div>
					<div className="whatsapp-float" id="whatsappFloat">
						<a
							href="https://api.whatsapp.com/send?phone=5215610197622&text=Hola,%20me%20gustaria%20obtener%20m%C3%A1s%20informaci%C3%B3n%20sobre%20sus%20productos"
							target="_blank"
							rel="noopener noreferrer"
							aria-label="Contactar por WhatsApp"
							className="whatsapp-button"
						>
							<WhatsApp className="size-8 fill-white" />
						</a>
						<div className="whatsapp-tooltip">¡Escríbenos!</div>
					</div>
				</footer>
			</body>
		</html>
	);
}
